version: "3.9"
services:
  database:
    image: postgres:13.8
    restart: always
    ports:
      - "5434:5432"
    environment:      
      POSTGRES_PASSWORD: postgres       
      POSTGRES_USER: postgres       
      POSTGRES_DB: referral_app  
      POSTGRES_HOST: localhost
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build:
      context: ./rails-api-app
      dockerfile: Dockerfile.local
    command: bash -c "rails db:environment:set RAILS_ENV=development && bundle exec rake db:migrate && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
    environment:      
      DATABASE_URL: postgres://postgres:postgres@database:5432/referral_app?encoding=utf8&pool=5&timeout=5000  
      REACT_HOST: http://localhost:3000/invite/accept
    volumes:
      - .:/rails-api-app
    depends_on:
      - database

  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    environment:      
      REACT_APP_API_HOST: http://localhost:3001/api/users  
    volumes:
      - ./react-app:/react-app
      - /react-app/node_modules

volumes:
  postgres: