AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'spec/**/*'
    - 'lib/**/*'
  NewCops: enable

Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false   
Style/GuardClause:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false     

